myapp/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
]

myapp/lunchmap/urls.py
from django.urls import path
from . import views

app_name = 'lunchmap'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views. DetailView.as_view(), name='detail'),
    path('creat/', views.CreateView.as_view(), name='create'),
    #path('creatcomment/', views.CreateView.as_view(), name='createcomment'),
    path('<int:pk>/update/', views.UpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.DeleteView.as_view(), name='delete'),
    path('comment/create/<int:pk>/',
         views.CommentCreate.as_view(), name='comment_create'),
]

myapp/myapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ideabox/', include('lunchmap.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', RedirectView.as_view(url='/ideabox/')),
]

myapp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('practice/', include('practice.urls')),
    path('admin/', admin.site.urls),
]

myapp/accounts/models.py
from django.db import models

# Create your models here.

myapp/lunchmap/models.py
from cgitb import text
from cmath import atan
from unicodedata import name
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=255)
    author = models.ForeignKey(
        "auth.User",
        on_delete=models.CASCADE,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Comment(models.Model):
    category = models.ForeignKey("Shop", on_delete=models.PROTECT, null=True)
    txt = models.CharField(max_length=255, null=True)

    def __str__(self):
        return self.txt


class Shop(models.Model):
    name = models.CharField(max_length=255)
    # address = models.CharField(max_length=255)
    description = models.CharField(max_length=255, null=True)
    category = models.ForeignKey(
        Category,
        on_delete=models.PROTECT,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    deadline_at = models.CharField(max_length=255, null=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("lunchmap:detail", kwargs={"pk": self.pk})

    def comments(self):
        return Comment.objects.filter(category=self)

myapp/accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

myapp/lunchmap/views.py
from pyexpat import model
from xml.etree.ElementTree import Comment
from django.shortcuts import render
from django.views import generic
from pyrsistent import field
from .models import Category, Shop, Comment
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404, redirect, render


class IndexView(generic.ListView):
    model = Shop


class DetailView(generic.DetailView):
    model = Shop


class CreateView(generic.edit.CreateView):
    model = Shop
    fields = '__all__'


class UpdateView(generic.edit.UpdateView):
    model = Shop
    fields = '__all__'


class DeleteView(generic.edit.DeleteView):
    model = Shop
    success_url = reverse_lazy('lunchmap:index')


class CommentCreate(generic.CreateView):
    """コメント投稿ページのビュー"""
    model = Comment
    success_url = reverse_lazy('lunchmap:index')
    fields = '__all__'
    #form_class = CommentCreateForm

myapp/lunchmap/templates/lunchmap/base.html
<!DOCTYPE html>
<html>
<style>
    .box1 {
        padding: 0.5em 1em;
        margin: 2em 0;
        background: -webkit-repeating-linear-gradient(-45deg, #f0f8ff, #f0f8ff 3px, #e9f4ff 3px, #e9f4ff 7px);
        background: repeating-linear-gradient(-45deg, #f0f8ff, #f0f8ff 3px, #e9f4ff 3px, #e9f4ff 7px);
    }

    .box1 p {
        margin: 0;
        padding: 0;
    }
</style>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
    <title>Lunchmap</title>

    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'>
    <style>
        body {
            padding-top: 80px;
        }
    </style>
</head>

<body>
    <nav class='navbar navbar-expand-md navbar-dark bg-dark fixed-top'>
        <a class='navbar-brand' href='{% url "lunchmap:index" %}'>idea-box</a>
    </nav>
    {% block content %}
    {% endblock %}
</body>

</html>

myapp/lunchmap/templates/lunchmap/comment_form.html
{% extends './base.html' %}
{% block content %}
<h1>コメント投稿</h1>
<form action='' method='post'>{% csrf_token %}
    {{form.as_p}}
    <button type='submit' class='submit'>投稿</button>
</form>
<div>
    <a href='JavaScript:history.back()'>&lt; 戻る</a>
</div>

{% endblock %}

myapp/lunchmap/templates/lunchmap/shop_confirm_delete.html
{% extends './base.html' %}
{% block content %}
<h1>お店情報の削除</h1>
<p>'{{object.name}}'を消去しますか？</p>

<form action='' method='post'>{% csrf_token %}

<button type='submit' class='submit delete'>削除する</button>
</form>
<div>
<a href='JavaScript:history.back()'>&lt; 戻る</a>
</div>

{% endblock %}

myapp/lunchmap/templates/lunchmap/shop_detail.html
{% extends './base.html' %}
{% block content %}
<h1>{{ shop.name }}</h1>
<div>
    <p>{{shop.description}}</p>
    <h2>コメント</h2>
    {% for comment in shop.comments %}
    <p>{{comment.txt}}</p>
    {% endfor %}
</div>
<div>
    <a href="{% url 'lunchmap:index' %}">一覧</a>
    <a href="{% url 'lunchmap:update' shop.pk %}">編集</a>
    <a href="{% url 'lunchmap:delete' shop.pk %}">削除</a>
    <a href="{% url 'lunchmap:comment_create' shop.pk %}">コメント投稿</a>
</div>

{% endblock %}

myapp/lunchmap/templates/lunchmap/shop_form.html
{% extends './base.html' %}
{% block content %}
<h1>情報の{{object|yesno:'更新,作成'}}</h1>
<form action='' method='post'>{% csrf_token %}
{{form.as_p}}
<button type='submit' class='submit'>{{ object|yesno:'更新,作成'}}</button>
</form>
<div>
<a href='JavaScript:history.back()'>&lt; 戻る</a>
</div>

{% endblock %}

myapp/lunchmap/templates/lunchmap/shop_list.html
{% extends './base.html' %}
{% block content %}
<h1>一覧</h1>
<table class='table table-striped table-hover'>
    <tr>
        <th>期限</th>
        <th>タイトル</th>
        <th>内容</th>
    </tr>



    {% for shop in object_list %}
    <tr>
        <td>{{ shop.deadline_at }}</td>
        <td><a href='{% url "lunchmap:detail" shop.pk %}'>{{ shop.name }}</a></td>
        <td>{{ shop.description }}</td>
    </tr>

    {% endfor %}
</table>

<div>
    <a href='{% url "lunchmap:create" %}'>新しい投稿</a>
</div>

{% endblock %}

myapp/templates/layout.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no">
    <title>Lunchmap</title>

    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css'>
    <style>
        body {
            padding-top: 80px;
        }
    </style>
</head>

<body>
    <nav class='navbar navbar-expand-md navbar-dark bg-dark fixed-top'>
        <a class='navbar-brand' href='{% url "lunchmap:index" %}'>lunchmap</a>
        <ul class='navbar-nav'>
                {% if user.is_authenticated %}
                    <li class='nav-item'>
                        <span class='navbar-text'>{{user}} - </span>
                    </li>
                    <li class='nav-item'>
                        <a href='{% url "logout" %}' class='logout nav-link'>logout</a>
                    </li>
                {% else %}
                    <a href='{% url "login" %}' class='login nav-link'>Login</a>
                {% endif %}
        </ul>
    </nav>
    {% block content %}
    {% endblock %}
</body>

</html>